// Package spdr registers the SP//dr hero (31001): the SP//dr Suit
// identity with its Interface-upgrade resource economy (Sync Ratio), the
// signature cards, the Inherited Burden obligation and the M.O.R.B.I.U.S.
// nemesis set.
//
// Approximations specific to this pack:
//   - The Peni Parker card (31002) is absent from the data snapshot, so
//     the suit's b side (31001b, a support) serves as the alter-ego side;
//     the detach/counter-transfer rules of Return to Base are not
//     modeled. Ejection Protocol's flip uses the generic form change.
//   - Sync Ratio is modeled by giving each Interface upgrade its own
//     hero resource hook (exhaust → its printed icon), which is exactly
//     the printed effect; riders keyed off "resources generated by Sync
//     Ratio" (VEN#m, Rapid Deployment, Web-Trap) cannot observe ability
//     payments and are omitted.
package spdr

import (
	"github.com/Knights-of-the-Found-Table/marvelchampionsnext/internal/engine"
	"github.com/Knights-of-the-Found-Table/marvelchampionsnext/internal/engine/cards/cardutil"
)

func init() {
	registerSPDR()
	registerSPDRSignatures()
	registerSPDRObligation()
	registerSPDRNemesis()
}

// interfaceUpgrades lists the player's in-play Interface upgrades.
func interfaceUpgrades(g *engine.Game, p *engine.Player) []*engine.Upgrade {
	var out []*engine.Upgrade
	for _, id := range p.Upgrades {
		if u := g.Upgrades[id]; u != nil && u.EDef().HasTrait("interface") {
			out = append(out, u)
		}
	}
	return out
}

// registerSPDR installs the SP//dr Suit identity (31001a/b).
func registerSPDR() {
	engine.RegisterBehavior("31001", &engine.Behavior{})
}

func registerSPDRSignatures() {
	// 31003 VEN#m: +1 THW/+1 ATK per sym counter and the Sync Ratio
	// payment rider are not modeled (see package comment); she plays as a
	// vanilla 1/1/3 ally with her printed wild... energy resource.
	engine.RegisterBehavior("31003", &engine.Behavior{})

	// 31004 All Systems Go!: Hero Action — choose: ready each Interface
	// upgrade you control, or search your deck and discard pile for an
	// Interface upgrade and add it to your hand (shuffle).
	engine.RegisterBehavior("31004", &engine.Behavior{
		OnPlay: func(g *engine.Game, e engine.Entity) []engine.Message {
			p := g.Player(e.EOwner())
			if p == nil {
				return nil
			}
			var choices []engine.Choice
			var readies []engine.Message
			for _, u := range interfaceUpgrades(g, p) {
				if u.Exhausted {
					readies = append(readies, engine.ReadyEntity{ID: u.ID})
				}
			}
			if len(readies) > 0 {
				choices = append(choices, engine.Choice{
					ID: "ready", Label: engine.Tf("c.readyEachInterfaceUpgradeYouControl"), Kind: engine.ChoiceLabel,
				}.Msgs(readies...))
			}
			for _, c := range p.Deck {
				if c.Def().HasTrait("interface") {
					choices = append(choices, engine.Choice{
						Label: engine.S(c.Def().Name + " (deck)"), Kind: engine.ChoiceCard, CardCode: c.Code,
					}.Msgs(
						engine.TakeDeckCard{Player: p.ID, CardID: c.ID},
						engine.ShufflePlayerDeck{Player: p.ID},
					))
				}
			}
			for _, c := range p.Discard {
				if c.Def().HasTrait("interface") {
					choices = append(choices, engine.Choice{
						Label: engine.S(c.Def().Name + " (discard)"), Kind: engine.ChoiceCard, CardCode: c.Code,
					}.Msgs(engine.ReturnDiscardCard{Player: p.ID, CardID: c.ID}))
				}
			}
			if len(choices) == 0 {
				return nil
			}
			return []engine.Message{engine.AskQuestion{
				Player:   p.ID,
				Question: engine.Ask(engine.Tf("c.allSystemsGoChoose"), choices...),
			}}
		},
	})

	// 31005 Rapid Deployment: Hero Action (thwart) — remove 3 threat
	// from a scheme. (Sync Ratio payment rider omitted, see package
	// comment.)
	engine.RegisterBehavior("31005", &engine.Behavior{
		OnPlay: cardutil.ChooseScheme(engine.Tf("c.rapidDeploymentChooseAScheme"), func(g *engine.Game, e engine.Entity) int { return 3 }),
	})

	// 31006 Web-Trap: Hero Action (attack) — deal 5 damage to an enemy.
	// (Sync Ratio stun rider omitted, see package comment.)
	engine.RegisterBehavior("31006", &engine.Behavior{
		OnPlay: cardutil.ChooseEnemy(engine.Tf("c.webTrapDeal5DamageToAnEnemy"),
			func(g *engine.Game, e engine.Entity) (int, []engine.Message) { return 5, nil }),
	})

	// 31007 Aunt May & Uncle Ben: Action — exhaust → discard the top 2
	// cards of your deck (top 3 in alter-ego form) and add each SP//dr
	// card discarded this way to your hand.
	engine.RegisterBehavior("31007", &engine.Behavior{
		Abilities: func(g *engine.Game, e engine.Entity) []engine.Ability {
			return []engine.Ability{{
				Label: engine.Tf("c.auntMayUncleBenMill23InAlterEgoKeepTheSpDrCards"), Type: engine.AbilityAction, Exhaust: true,
				Execute: func(g *engine.Game, self engine.EntityID) []engine.Message {
					s := g.Supports[self]
					p := g.Player(e.EOwner())
					if s == nil || p == nil {
						return nil
					}
					n := 2
					if !p.IsHero() {
						n = 3
					}
					if len(p.Deck) == 0 {
						return nil
					}
					if len(p.Deck) < n {
						n = len(p.Deck)
					}
					milled := append(engine.CardList{}, p.Deck[:n]...)
					p.Deck = p.Deck[n:]
					var kept []string
					var rest engine.CardList
					for _, c := range milled {
						if c.Def().CardSet == "spdr" {
							p.Hand = append(p.Hand, c)
							kept = append(kept, c.Def().Name)
						} else {
							rest = append(rest, c)
						}
					}
					p.Discard = append(p.Discard, rest...)
					if len(kept) > 0 {
						g.TLogf("c.auntMayUncleBenKeeps", p.Name, kept)
					}
					return nil
				},
			}}
		},
	})

	// 31008 Ejection Protocol: Hero Action — discard → exhaust each
	// Interface upgrade you control, set your hit point dial to 6, gain
	// tough, and flip to alter-ego form.
	engine.RegisterBehavior("31008", &engine.Behavior{
		Abilities: func(g *engine.Game, e engine.Entity) []engine.Ability {
			return []engine.Ability{{
				Label: engine.Tf("c.ejectionProtocolEjectPeniHpTo6ToughFlipToAlterEgo"), Type: engine.AbilityAction, HeroOnly: true,
				Execute: func(g *engine.Game, self engine.EntityID) []engine.Message {
					s := g.Supports[self]
					p := g.Player(e.EOwner())
					if s == nil || p == nil {
						return nil
					}
					msgs := []engine.Message{engine.DiscardControlled{Player: p.ID, ID: s.ID}}
					for _, u := range interfaceUpgrades(g, p) {
						if !u.Exhausted {
							msgs = append(msgs, engine.ExhaustEntity{ID: u.ID})
						}
					}
					if d := p.MaxHP - 6; d >= 0 {
						p.Damage = d
					}
					msgs = append(msgs,
						engine.ToughEntity{Target: p.ID},
						engine.ChangeForm{Player: p.ID},
					)
					g.TLogf("c.ejectionProtocolEjects", p.Name)
					return msgs
				},
			}}
		},
	})

	// 31009 SP//dr Command: two hero actions — exhaust Command + an
	// Interface upgrade → draw 1; exhaust Command + discard 1 hand card
	// → ready an Interface upgrade.
	engine.RegisterBehavior("31009", &engine.Behavior{
		Abilities: func(g *engine.Game, e engine.Entity) []engine.Ability {
			s := g.Supports[e.EID()]
			p := g.Player(e.EOwner())
			if s == nil || p == nil {
				return nil
			}
			var out []engine.Ability
			hasReady := false
			hasExhausted := false
			for _, u := range interfaceUpgrades(g, p) {
				if !u.Exhausted {
					hasReady = true
				} else {
					hasExhausted = true
				}
			}
			if hasReady {
				out = append(out, engine.Ability{
					Label: engine.Tf("c.spDrCommandExhaustAnInterfaceUpgradeDraw1Card"), Type: engine.AbilityAction,
					HeroOnly: true, Exhaust: true,
					Execute: func(g *engine.Game, self engine.EntityID) []engine.Message {
						s := g.Supports[self]
						p := g.Player(s.Owner)
						var choices []engine.Choice
						for _, u := range interfaceUpgrades(g, p) {
							if u.Exhausted {
								continue
							}
							choices = append(choices, engine.Choice{
								Label: engine.S(u.EDef().Name), Kind: engine.ChoiceTarget, SourceID: u.ID, CardCode: u.Code,
							}.Msgs(
								engine.ExhaustEntity{ID: u.ID},
								engine.DrawCards{Player: p.ID, N: 1},
							))
						}
						if len(choices) == 0 {
							return nil
						}
						return []engine.Message{engine.AskQuestion{
							Player:   p.ID,
							Question: engine.Ask(engine.Tf("c.spDrCommandExhaustWhichInterfaceUpgrade"), choices...),
						}}
					},
				})
			}
			if hasExhausted && len(p.Hand) > 0 {
				out = append(out, engine.Ability{
					Label: engine.Tf("c.spDrCommandDiscard1CardReadyAnInterfaceUpgrade"), Type: engine.AbilityAction,
					HeroOnly: true, Exhaust: true,
					Execute: func(g *engine.Game, self engine.EntityID) []engine.Message {
						s := g.Supports[self]
						p := g.Player(s.Owner)
						var choices []engine.Choice
						for _, c := range p.Hand {
							c := c
							var ups []engine.Choice
							for _, u := range interfaceUpgrades(g, p) {
								if !u.Exhausted {
									continue
								}
								ups = append(ups, engine.Choice{
									Label: engine.S(u.EDef().Name), Kind: engine.ChoiceTarget, SourceID: u.ID, CardCode: u.Code,
								}.Msgs(
									engine.DiscardCards{Player: p.ID, Cards: engine.CardList{c}},
									engine.ReadyEntity{ID: u.ID},
								))
							}
							if len(ups) > 0 {
								choices = append(choices, engine.Choice{
									Label: engine.S("Discard " + c.Def().Name), Kind: engine.ChoiceCard, CardCode: c.Code,
								}.WithThen(engine.Ask(engine.Tf("c.readyWhichInterfaceUpgrade"), ups...)))
							}
						}
						if len(choices) == 0 {
							return nil
						}
						return []engine.Message{engine.AskQuestion{
							Player:   p.ID,
							Question: engine.Ask(engine.Tf("c.spDrCommandDiscard1Card"), choices...),
						}}
					},
				})
			}
			return out
		},
	})

	// 31010 Host Spider (Interface): Sync Ratio resource [wild]; Hero
	// Action — exhaust → ready SP//dr Suit.
	engine.RegisterBehavior("31010", &engine.Behavior{
		Resource: &engine.ResourceAbility{Icon: "wild", HeroOnly: true},
		Abilities: func(g *engine.Game, e engine.Entity) []engine.Ability {
			return []engine.Ability{{
				Label: engine.Tf("c.hostSpiderReadySpDrSuit"), Type: engine.AbilityAction, HeroOnly: true, Exhaust: true,
				Execute: func(g *engine.Game, self engine.EntityID) []engine.Message {
					return []engine.Message{engine.ReadyEntity{ID: e.EOwner()}}
				},
			}}
		},
	})

	// 31011 Psychic Link (Interface): Sync Ratio resource [mental]; Hero
	// Interrupt — when SP//dr Suit makes a basic thwart, exhaust → +2 THW
	// for that thwart. (Approximation: the +2 lands as follow-up threat
	// removal on the same scheme, the Nick Fury precedent.)
	engine.RegisterBehavior("31011", &engine.Behavior{
		Resource: &engine.ResourceAbility{Icon: "mental", HeroOnly: true},
		React: func(g *engine.Game, e engine.Entity, msg engine.Message) []engine.Message {
			m, ok := msg.(engine.BasicThwart)
			if !ok {
				return nil
			}
			u := g.Upgrades[e.EID()]
			if u == nil || u.Exhausted {
				return nil
			}
			p := g.Player(u.Owner)
			if p == nil || !p.IsHero() || m.Player != p.ID {
				return nil
			}
			g.TLogf("c.psychicLink2ThreatRemoval")
			return []engine.Message{
				engine.ExhaustEntity{ID: u.ID},
				engine.ThwartScheme{Scheme: m.Target, N: 2, Source: u.ID},
			}
		},
	})

	// 31012 Speed-Metal Alloy (Interface): Sync Ratio resource
	// [physical]; Hero Interrupt — when SP//dr Suit defends, exhaust →
	// +2 DEF for that defense. (Approximation: offered as a substitute
	// defense in the defense prompt, the Bamf! channel.)
	engine.RegisterBehavior("31012", &engine.Behavior{
		Resource: &engine.ResourceAbility{Icon: "physical", HeroOnly: true},
		DefenseSubstitute: func(g *engine.Game, p *engine.Player, u *engine.Upgrade, against engine.EntityID) (engine.Defends, []engine.Message, bool) {
			if !p.IsHero() || u.Exhausted {
				return engine.Defends{}, nil, false
			}
			d := engine.Defends{Defender: p.ID, Against: against, DefBonus: 2}
			return d, []engine.Message{engine.ExhaustEntity{ID: u.ID}}, true
		},
	})

	// 31013 Web-Fluid Compressor (Interface): Sync Ratio resource
	// [energy]; Hero Interrupt — when SP//dr Suit makes a basic attack,
	// exhaust → +2 ATK for that attack. (Same follow-up damage
	// approximation as Psychic Link.)
	engine.RegisterBehavior("31013", &engine.Behavior{
		Resource: &engine.ResourceAbility{Icon: "energy", HeroOnly: true},
		React: func(g *engine.Game, e engine.Entity, msg engine.Message) []engine.Message {
			m, ok := msg.(engine.BasicAttack)
			if !ok {
				return nil
			}
			u := g.Upgrades[e.EID()]
			if u == nil || u.Exhausted {
				return nil
			}
			p := g.Player(u.Owner)
			if p == nil || !p.IsHero() || m.Player != p.ID {
				return nil
			}
			g.TLogf("c.webFluidCompressor2Damage")
			return []engine.Message{
				engine.ExhaustEntity{ID: u.ID},
				engine.DamageEntity{Target: m.Target, Damage: 2, Source: u.ID},
			}
		},
	})
}

// registerSPDRObligation installs Inherited Burden (31025): exhaust Peni
// to remove it, or discard an Interface upgrade you control.
func registerSPDRObligation() {
	engine.RegisterBehavior("31025", &engine.Behavior{
		ResolveObligation: func(g *engine.Game, p *engine.Player, card engine.Card) []engine.Message {
			exhaust := engine.Choice{
				ID: "exhaust", Label: engine.Tf("c.exhaustPeniParkerRemoveInheritedBurdenFromTheGame"), Kind: engine.ChoiceLabel,
			}.Msgs(
				engine.ExhaustEntity{ID: p.ID},
				engine.ObligationResolve{Player: p.ID, Card: card, Remove: true},
			)
			choices := []engine.Choice{exhaust}
			var discardChoices []engine.Choice
			for _, u := range interfaceUpgrades(g, p) {
				discardChoices = append(discardChoices, engine.Choice{
					Label: engine.S(u.EDef().Name), Kind: engine.ChoiceTarget, SourceID: u.ID, CardCode: u.Code,
				}.Msgs(
					engine.DiscardControlled{Player: p.ID, ID: u.ID},
					engine.ObligationResolve{Player: p.ID, Card: card},
				))
			}
			discard := engine.Choice{
				ID: "discard", Label: engine.Tf("c.discardAnInterfaceUpgradeYouControl"), Kind: engine.ChoiceLabel,
			}
			if len(discardChoices) > 0 {
				discard = discard.WithThen(engine.Ask(engine.Tf("c.discardWhichInterfaceUpgrade"), discardChoices...))
			} else {
				discard = discard.Msgs(engine.ObligationResolve{Player: p.ID, Card: card})
			}
			choices = append(choices, discard)
			return []engine.Message{engine.AskQuestion{
				Player:   p.ID,
				Question: engine.Ask(engine.Tf("c.inheritedBurdenChoose"), choices...),
			}}
		},
	})
}

// registerSPDRNemesis installs the SP//dr nemesis set (Giant Monster
// Attack, M.O.R.B.I.U.S., Energy Drain).
func registerSPDRNemesis() {
	// 31026 Giant Monster Attack: the [energy] additional thwart cost is
	// not representable in the thwart cost hook; the scheme plays as a
	// plain 4-threat side scheme.
	engine.RegisterBehavior("31026", &engine.Behavior{})

	// 31027 M.O.R.B.I.U.S.: Forced Response — after the engaged hero
	// generates any number of resources, deal an equal amount of damage
	// to that hero. (Approximation: hooked on hand-card resource payments
	// — one damage per resource icon spent; resource abilities do not
	// emit an observable event.)
	engine.RegisterBehavior("31027", &engine.Behavior{
		React: func(g *engine.Game, e engine.Entity, msg engine.Message) []engine.Message {
			m, ok := msg.(engine.ResourcePay)
			if !ok {
				return nil
			}
			mn := g.Minions[e.EID()]
			if mn == nil || mn.EngagedWith != m.Player {
				return nil
			}
			p := g.Player(m.Player)
			if p == nil || !p.IsHero() {
				return nil
			}
			n := 0
			for _, c := range m.Cards {
				n += len(c.Def().Resources)
			}
			if n == 0 {
				return nil
			}
			g.TLogf("c.mORBIUSTakesDamageForGeneratingResources", p.Name, n)
			return []engine.Message{engine.DamageEntity{Target: p.ID, Damage: n, Source: mn.ID}}
		},
	})

	// 31028 Energy Drain: When Revealed — spend [energy][energy] or
	// suffer: exhaust your identity (alter-ego) / take 3 damage (hero).
	// (Approximation: the resource-spend escape is not enforceable, so
	// the penalty always applies.)
	engine.RegisterBehavior("31028", &engine.Behavior{
		ResolveTreachery: func(g *engine.Game, t *engine.Treachery, p *engine.Player) []engine.Message {
			g.Delete(t.ID)
			if p.IsHero() {
				return []engine.Message{engine.DamageEntity{Target: p.ID, Damage: 3, Source: t.ID}}
			}
			return []engine.Message{engine.ExhaustEntity{ID: p.ID}}
		},
	})
}
